draw_config:
  append_colon_to_layer_header: false
  key_w: 60
  key_h: 56
  split_gap: 30.0
  combo_w: 26
  combo_h: 26
  key_rx: 6.0
  key_ry: 6.0
  dark_mode: false
  n_columns: 1
  separate_combo_diagrams: false
  combo_diagrams_scale: 2
  inner_pad_w: 2.0
  inner_pad_h: 2.0
  outer_pad_w: 30.0
  outer_pad_h: 56.0
  line_spacing: 1.2
  arc_radius: 6.0
  small_pad: 2.0
  legend_rel_x: 0.0
  legend_rel_y: 0.0
  draw_key_sides: false
  key_side_pars:
    rel_x: 0.0
    rel_y: 4.0
    rel_w: 12.0
    rel_h: 12.0
    rx: 4.0
    ry: 4.0
  svg_extra_style: |-
    :root {
      --color-bg: #8ACB88;
      --color-primary: #E4FDE1;
      --color-secondary: #575761;
      --color-accent: #e9ea04;
      --color-gray: #333;
    }

    text.label {
        font-size: 36px;
        text-anchor: start;
        paint-order: stroke;
        fill: var(--color-gray);
        translate: 394px 105px;
        stroke-width: 0;
        font-size: 24px;
    }
    .layer-Fn text.label {
        translate: 394px 105px;
    }

    rect.key {
      fill: var(--color-primary);
      stroke-width: 0;
    }

    rect.key.held {
      fill: var(--color-accent);
    }

    text.key, .key.glyph {
      fill: var(--color-secondary);
      color: var(--color-secondary);
    }

    rect.combo {
      rx: 50%;
      ry: 50%;
      stroke-width: 0;
      fill: var(--color-secondary);
    }

    .combo path {
      stroke: var(--color-secondary);
      stroke-dasharray: 4 3;
    }

    .combo text, .combo.glyph {
      color: var(--color-primary);
      fill: var(--color-primary);
    }

    svg.keymap {
      background: var(--color-bg);
      font-family: Roboto, Arial;
    }

    .footer {
     display: none;
    }

    .layer-NUM .combo, .layer-NAV .combo {
      display: none;
    }
  footer_text: ""
  shrink_wide_legends: 5
  style_layer_activators: true
  glyph_tap_size: 14
  glyph_hold_size: 12
  glyph_shifted_size: 10
  glyphs: {}
parse_config:
  preprocess: true
  skip_binding_parsing: false
  raw_binding_map: {}
  sticky_label: sticky
  toggle_label: toggle
  tap_toggle_label: tap-toggle
  trans_legend:
    t: $$phosphor:bold/triangle$$
    type: trans
  layer_legend_map: {}
  mark_alternate_layer_activators: false
  modifier_fn_map:
    left_ctrl: ^
    right_ctrl: ^
    left_shift: SH 
    right_shift: SH 
    left_alt: Alt
    right_alt: AltGr
    left_gui: GUI
    right_gui: GUI
    keycode_combiner: '{mods} {key}'
    mod_combiner: '{mod_1} {mod_2}'
    special_combinations:
      left_gui+left_ctrl+left_arrow: XYZ
      left_ctrl+left_gui+left_arrow: YZZ
      left_ctrl+left_alt+left_gui+left_shift: Hyper
      left_ctrl+left_alt+left_shift: Meh
  zmk_remove_keycode_prefix: []
  zmk_keycode_map:
    PRINTSCREEN: PRNT
    LSHIFT: $$phosphor:bold/arrow-fat-up$$
    LSHFT: $$phosphor:bold/arrow-fat-up$$
    RSHIFT: $$phosphor:bold/arrow-fat-up$$
    RSHFT: $$phosphor:bold/arrow-fat-up$$
    RCTRL: $$phosphor:bold/control$$
    LCTRL: $$phosphor:bold/control$$
    SPACE: $$mdi:keyboard-space$$
    ARROW_LEFT: $$phosphor:bold/arrow-left$$
    ARROW_RIGHT: $$phosphor:bold/arrow-right$$
    ARROW_UP: $$phosphor:bold/arrow-up$$
    ARROW_DOWN: $$phosphor:bold/arrow-down$$
    TAB: $$phosphor:bold/arrow-line-right$$
    ESC: $$phosphor:bold/x-circle$$
    BACKSPACE: $$phosphor:bold/backspace$$
    RET: $$phosphor:bold/key-return$$
    C_MUTE: $$phosphor:bold/speaker-slash$$
    C_VOL_UP: $$phosphor:bold/speaker-high$$
    C_VOL_DN: $$phosphor:bold/speaker-low$$
    C_NEXT: $$phosphor:bold/skip-forward$$
    C_PREV: $$phosphor:bold/skip-back$$
    C_PP: $$phosphor:bold/play-pause$$
    C_PLAY_PAUSE: $$phosphor:bold/play-pause$$
    C_STOP: $$phosphor:bold/stop$$
    LALT: Alt
    RALT: AltGr
    RCMD: GUI
    LCMD: GUI
    LGUI: GUI
    RGUI: GUI
    EXCLAMATION: '!'
    EXCL: '!'
    AT_SIGN: '@'
    AT: '@'
    HASH: '#'
    POUND: '#'
    DOLLAR: $
    DLLR: $
    PERCENT: '%'
    PRCNT: '%'
    CARET: ^
    AMPERSAND: '&'
    AMPS: '&'
    ASTERISK: '*'
    ASTRK: '*'
    STAR: '*'
    LEFT_PARENTHESIS: (
    LPAR: (
    RIGHT_PARENTHESIS: )
    RPAR: )
    EQUAL: '='
    PLUS: +
    MINUS: '-'
    UNDERSCORE: _
    UNDER: _
    SLASH: /
    FSLH: /
    QUESTION: '?'
    QMARK: '?'
    BACKSLASH: \
    BSLH: \
    PIPE: '|'
    NON_US_BACKSLASH: \
    PIPE2: '|'
    NON_US_BSLH: '|'
    SEMICOLON: ;
    SEMI: ;
    COLON: ':'
    SINGLE_QUOTE: ''''
    SQT: ''''
    APOSTROPHE: ''''
    APOS: ''''
    DOUBLE_QUOTES: '"'
    DQT: '"'
    COMMA: ','
    LESS_THAN: <
    LT: <
    PERIOD: .
    DOT: .
    GREATER_THAN: '>'
    GT: '>'
    LEFT_BRACKET: '['
    LBKT: '['
    LEFT_BRACE: '{'
    LBRC: '{'
    RIGHT_BRACKET: ']'
    RBKT: ']'
    RIGHT_BRACE: '}'
    RBRC: '}'
    GRAVE: '`'
    TILDE: '~'
    NON_US_HASH: '#'
    NUHS: '#'
    TILDE2: '~'
  zmk_combos:
    c_bspc:
      k: $$phosphor:bold/backspace$$
    c_esc:
      k: $$phosphor:bold/x-circle$$
    c_cut:
      k: $$phosphor:bold/file-x$$
      a: bottom
      o: 0.1
    c_paste:
      k: $$phosphor:bold/file-plus$$
    c_cpy:
      k: $$phosphor:bold/files$$
    c_tab:
      k: $$phosphor:bold/arrow-line-right$$
  zmk_preamble: '#define KEYMAP_DRAWER'
  zmk_additional_includes: []
